services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: simplepass
      POSTGRES_USER: dozer
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  dozer:
    depends_on:
      - postgres
    build: .
    volumes:
      - ".:/app"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./docs/_build/html:/usr/share/nginx/html:ro"
      
volumes:
  database:
