attacks = [
    "**{opponent}** was hit on the head by **{attacker}** ",
    "**{opponent}** was kicked by **{attacker}** ",
    "**{opponent}** was slammed into a wall by **{attacker}** ",
    "**{opponent}** was dropkicked by **{attacker}** ",
    "**{opponent}** was DDoSed by **{attacker}** ",
    "**{opponent}** was chokeslammed by **{attacker}** ",
    "**{opponent}** was run over with a robot by **{attacker}** ",
    "**{opponent}** had their IQ dropped 15 points by **{attacker}**",
    "**{opponent}** had a heavy object dropped on them by **{attacker}**",
    "**{opponent}** was beat up by **{attacker}** ",
    "**{opponent}** was told to read the manual by **{attacker}** ",
    "**{opponent}** was told to use windows by **{attacker}**",
    "**{opponent}** was forced to update windows by **{attacker}**",
    "**{opponent}** was E-stopped by **{attacker}** ",
    "**{opponent}** was hit by a snowplow driven by **{attacker}**",
    "**{opponent}** had their api token leaked by **{attacker}**",
    "**{opponent}** had a satellite dropped on them by **{attacker}**",
    "**{opponent}** lost connection to the field courtesy of **{attacker}**",
    "**{opponent}** was knocked off the hab by **{attacker}**",
    "**{opponent}** had the scale dropped on them by **{attacker}**",
    "**{opponent}** had `git rm --force` executed on them by **{attacker}**",
    # this and the following messages up to the next comment are custom by @transorsmth#7483
    "**{opponent}** had their autonomous broken by **{attacker}**",
    "**{opponent}** was voted out by **{attacker}**",
    "**{opponent}** was called sus by **{attacker}**",
    "**{opponent}** was hit with a power cell by **{attacker}**",
    "**{opponent}** had their main breaker pressed by **{attacker}**",
    "**{opponent}** had a conflicting autonomous with **{attacker}**",
    "**{opponent}** was hit with a stapler by **{attacker}**",
    "**{opponent}** was knocked off the traversal bar by **{attacker}**",
    "**{opponent}** had their battery fall out out thanks to **{attacker}**",
    "**{opponent}** had their season ended by **{attacker}**",
    "**{opponent}** had their roborio bricked by **{attacker}**",
    # this and the following messages are thanks to J-Man from the CHS discord server, who expended their
    # creative powers on these statements.
    "**{opponent}** extended too far outside their frame perimeter in front of **{attacker}**",
    "**{opponent}** lost a coffee-drinking competition against **{attacker}**",
    "**{opponent}** was a no-show against **{attacker}**",
    "**{opponent}** fell asleep before a match against **{attacker}**",
    "**{opponent}** yelled ROBOT! too loudly at **{attacker}**",
    "**{opponent}** got caught running in the pits by **{attacker}**",
    "**{opponent}** had their robot disabled by **{attacker}**",
    "**{opponent}** got a red card from **{attacker}**",
    "**{opponent}** got a yellow card from **{attacker}**",
    "**{opponent}** failed their robot's inspection by **{attacker}**",
    "**{opponent}** had their firewall re-enabled by **{attacker}**",
    "**{opponent}** had their drill battery stolen by **{attacker}**",
    "**{opponent}** had their website hacked by **{attacker}**",
    "**{opponent}** got their head zipped in a power cube by **{attacker}**",
    "**{opponent}** lost their sponsorship to **{attacker}**",
    "**{opponent}** took an arrow in the knee from **{attacker}**",
    "**{opponent}** was given a tech foul by **{attacker}**",
    "**{opponent}** had their code corrupted by **{attacker}**",
    "**{opponent}** was found without adequate eye protection by **{attacker}**",
    "**{opponent}** was knocked off the chain by **{attacker}**"
]